apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  environment: prod

patchesStrategicMerge:
- ./deploy-replicas-patch.yaml

configMapGenerator:
- name: lol-champions-app-configuration
  envs:
  - properties.env

secretGenerator:
- name: lol-champions-app-secured-configuration
  envs:
  - secured.env

images:
- name: lol-champions-app
  newName: image-registry.openshift-image-registry.svc:5000/ci-cd-workspace/lol-champions-app
  newTag: 1.0.0-init