---
# Currently using default ArgoCD instance (created by operator)
# Just checking/waiting until argocd is healthy
- name: Wait for ArgoCD to be running
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
  register: argocd_info
  until: argocd_info.resources | length > 0 and argocd_info.resources[0].status.phase == "Available"
  retries: 30
  delay: 10

- name: Grant admin access to ArgoCD in demo namespaces
  kubernetes.core.k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: argocd-admin
        namespace: "{{ namespace.name }}"
      subjects:
        - kind: ServiceAccount
          name: openshift-gitops-argocd-application-controller
          namespace: openshift-gitops
      roleRef:
        kind: ClusterRole
        name: admin
        apiGroup: rbac.authorization.k8s.io
  loop: "{{ demoNamespaces }}"
  loop_control:
    loop_var: namespace