apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-maven
  namespace: ci-cd-workspace
  annotations:
    argocd.argoproj.io/sync-wave: "48"
spec:
  description: >-
    This Task is used to run a maven command and optionally print an output file
  workspaces:
    - name: source
      description: The workspace consisting of maven project.
  params:
    - name: PATH_CONTEXT
      type: string
    - name: MAVEN_COMMAND
      type: string
  steps:
    - name: run-command
      image: maven:3.8.1-openjdk-17-slim
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      script: |
        
        /usr/bin/mvn $(params.MAVEN_COMMAND)