apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  environment: prod

secretGenerator:
- name: lol-champions-db-secured-configuration
  envs:
  - secured.env