apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: lol-champions-db
  app.kubernetes.io/part-of: lol-champions
  app.openshift.io/runtime: postgresql

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

images:
- name: postgres
  newName: image-registry.openshift-image-registry.svc:5000/openshift/postgresql
  newTag: 10-el8