apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-environment #Do not change this name (or update uninstall playbook)
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/clbartolome/openshift-devops.git
    targetRevision: master
    path: installation/environment/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true