---
- name: Install Demo in OpenShift
  hosts: localhost
  
  tasks:
    - name: Create Demo namespaces
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ namespace.name }}"
      loop: "{{ demoNamespaces }}"
      loop_control:
        loop_var: namespace

    - name: Install Operators
      include_role:
        name: install_operators

    - name: ArgoCD
      include_role:
        name: argo_cd

    - name: Demo Environment
      include_tasks: create_demo_environment.yaml
          
    - name: Display message after role execution
      debug:
        msg: "Running tasks after role execution"
  
  vars_files:
    - vars.yaml